### ISSUE TITLE
Support HTTPS hostname

### ISSUE THREAD

**Issue by sahar2339** [dana-team/container-app-operator#4]
We need to support `https` for the shortened hostname. 
by adding `HTTPS:true` to the `RouteSpec` the controller should inject secret to the `tls` option in the `DomainMapping` resource.

example:
```
apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: capp-secured
spec:
  configurationSpec:
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
          image: example-python-app
          name: python
  routeSpec:
    hostname: test.com
    HTTPS: true
```
